site_name: OpenAIRE Usage Counts Guidelines
site_author: OpenAIRE Usage Accounts Team
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - rust
nav:
    - Home: index.md
    - Service Specification: service-specification/service-spec.md
